<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   <?php
   for($b=0;$b<count($fila);$b++)
   {
       ?>
        <tr>
        <script src="js/funciones.js"></script>
            <td><?php echo $fila[$b]['id_usuario'];?></td>
            <td><?php echo $fila[$b]['nom_usuario'];?></td>
            <td><?php echo $fila[$b]['correo_usuario'];?></td>
            <td><?php echo $fila[$b]['id_perfil'];?></td>
            <td><?php echo $fila[$b]['usuario'];?></td>
            <td><?php echo $fila[$b]['contraseña'];?></td>
            <?php
            if (!(isset($_GET['m']) and $_GET['m'] == 1)) {
                ?>
                <td><a href="#" title="Editar datos del usuario" onClick="window.location='editar_usuario.php?id=<?php echo $fila[$b]['id_usuario']; ?>'"><i class="fas fa-pencil-alt"></i></a></td>
                <td><a href="#" title="Eliminar datos del usuario" onClick="eliminar(<?php echo $fila[$b]['id_usuario']; ?>,'eliminar_usuario.php');"><i class="fas fa-trash"></i></a></td>
        
            </tr>
            <?php
            }
    }
    ?>
</body>
</html>