<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./css/tabla.css">
    <title>Document</title>
</head>
<body>
   <?php
   for($b=0;$b<count($fila);$b++)
   {
       ?>
        <tr>
        <script src="js/funciones.js"></script>
            <td class="td-id"><?php echo $fila[$b]['id_videojuego'];?></td>
            <td><?php echo $fila[$b]['codigo'];?></td>
            <td><?php echo $fila[$b]['nom_game'];?></td>
            <td class="td-des"><?php echo $fila[$b]['des_game'];?></td>
            <td><?php echo $fila[$b]['cat_game'];?></td>
            <td><?php echo $fila[$b]['stock'];?></td>
            <td><?php echo $fila[$b]['precio_game'];?></td>
            <td><?php echo $fila[$b]['creador_game'];?></td>
            <td> <img src="<?php echo $fila[$b]['img_game'];?>" alt="" class="imgvideojuego"></td>
            <?php
            if (!(isset($_GET['m']) and $_GET['m'] == 1)) {
                ?>
                <td><a href="#" title="Editar datos del videojuego" onClick="window.location='editar_videojuegos.php?id=<?php echo $fila[$b]['id_videojuego']; ?>'"><i class="fas fa-pencil-alt"></i></a></td>
                <td><a href="#" title="Eliminar datos del videojuego" onClick="eliminar(<?php echo $fila[$b]['id_videojuego']; ?>,'eliminar_videojuegos.php');"<i class="fas fa-trash"></i></a></td>
        
            </tr>
            <?php
            }
    }
    ?>
</body>
</html>